"""Add timestamp to SensorData model

Revision ID: 0f029e896f79
Revises: 5f110d20f38e
Create Date: 2024-11-04 09:08:46.602685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f029e896f79'
down_revision = '5f110d20f38e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
